export const mockRefuges = [
    {
        id: 'ref1',
        name: 'State Library Reading Room',
        type: 'library',
        address: '328 Swanston St',
        suburb: 'Melbourne VIC 3000',
        distanceM: 210,
        walkMinutes: 3,
        crowdLevel: 'low',
        features: ['Silent zone', 'Comfortable seating', 'Dim adjustable lighting', 'Climate controlled', 'Accessible entry'],
        hours: 'Mon–Thu 10am–9pm · Fri–Sun 10am–6pm',
        sensoryScore: 92,
        sunflower: true,
    },
    {
        id: 'ref2',
        name: 'Treasury Gardens',
        type: 'park',
        address: 'Spring St',
        suburb: 'East Melbourne VIC 3002',
        distanceM: 380,
        walkMinutes: 5,
        crowdLevel: 'low',
        features: ['Open green space', 'Natural tree canopy', 'Quiet walking paths', 'Shaded benches', 'No vehicle noise'],
        hours: 'Open 24 hours',
        sensoryScore: 88,
        sunflower: false,
    },
    {
        id: 'ref3',
        name: 'Emporium Quiet Lounge',
        type: 'indoor',
        address: '287 Lonsdale St',
        suburb: 'Melbourne VIC 3000',
        distanceM: 290,
        walkMinutes: 4,
        crowdLevel: 'low',
        features: ['Sunflower scheme partner', 'Seating alcoves', 'Water station', 'Dimmed lighting'],
        hours: 'Mon–Thu 10am–7pm · Fri 10am–9pm · Sat–Sun 10am–7pm',
        sensoryScore: 80,
        sunflower: true,
    },
    {
        id: 'ref4',
        name: 'Flagstaff Gardens',
        type: 'garden',
        address: 'William St',
        suburb: 'Melbourne VIC 3000',
        distanceM: 680,
        walkMinutes: 9,
        crowdLevel: 'low',
        features: ['Large open lawns', 'Very low foot traffic', 'Tall tree canopy', 'No vehicle traffic inside', 'Multiple entry/exit points'],
        hours: 'Open 24 hours',
        sensoryScore: 95,
        sunflower: false,
    },
    {
        id: 'ref5',
        name: 'City Library',
        type: 'library',
        address: '253 Flinders Lane',
        suburb: 'Melbourne VIC 3000',
        distanceM: 140,
        walkMinutes: 2,
        crowdLevel: 'medium',
        features: ['Quiet study areas', 'Accessible seating', 'Calm atmosphere', 'Gender-neutral restrooms'],
        hours: 'Mon–Fri 8am–6pm · Sat 10am–5pm · Closed Sun',
        sensoryScore: 74,
        sunflower: false,
    },
    {
        id: 'ref6',
        name: 'Birrarung Marr Riverside',
        type: 'park',
        address: 'Batman Ave',
        suburb: 'Melbourne VIC 3000',
        distanceM: 450,
        walkMinutes: 6,
        crowdLevel: 'low',
        features: ['Riverside views', 'Open space', 'Natural water sounds', 'Low visual stimulation', 'Accessible pathways'],
        hours: 'Open 24 hours',
        sensoryScore: 90,
        sunflower: false,
    },
]