export const mockAlerts = [
    {
        id: 'a1',
        title: 'High Pedestrian Density',
        location: 'Swanston St between Flinders and Collins',
        type: 'crowd',
        severity: 'high',
        description: 'Peak commuter traffic. Approx 1,200 pedestrians per hour. Noise levels elevated significantly above average. Narrow footpath creates pinch points.',
        distanceM: 180,
        since: '8:15 AM',
        predictedEnd: '9:45 AM',
    },
    {
        id: 'a2',
        title: 'Active Construction Zone',
        location: 'Collins St at Queen St intersection',
        type: 'construction',
        severity: 'high',
        description: 'Heavy machinery in operation. Drilling sounds, bright flashing safety lights, and significant detour signage. Walkway width reduced to 1.2m.',
        distanceM: 320,
        since: '7:00 AM',
        predictedEnd: '5:00 PM',
    },
    {
        id: 'a3',
        title: 'Public Demonstration',
        location: 'Treasury Gardens, Spring St',
        type: 'event',
        severity: 'medium',
        description: 'Estimated 400 attendees. Loud speaker system, rhythmic chanting. Area partially cordoned by police. Overflow pedestrians onto footpaths.',
        distanceM: 650,
        since: '9:00 AM',
        predictedEnd: '12:00 PM',
    },
    {
        id: 'a4',
        title: 'Elevated Law Enforcement',
        location: 'Bourke St Mall',
        type: 'enforcement',
        severity: 'medium',
        description: 'Visible police operation underway. Additional uniformed patrols, radio communications audible. May be distressing for some individuals.',
        distanceM: 410,
        since: '8:30 AM',
        predictedEnd: '10:30 AM',
    },
    {
        id: 'a5',
        title: 'Moderate Crowd Build-up',
        location: 'Elizabeth St near Flinders',
        type: 'crowd',
        severity: 'low',
        description: 'Above-average pedestrian volume near tram stops 1 and 3. Expected to clear within 30 minutes as peak disperses.',
        distanceM: 90,
        since: '8:45 AM',
        predictedEnd: '9:15 AM',
    },
]

export const mockPredictive = [
    { time: '10:00 AM', zone: 'Swanston St', pct: 92, level: 'high', reason: 'Post-peak commuter surge' },
    { time: '11:30 AM', zone: 'Bourke St Mall', pct: 78, level: 'high', reason: 'Lunch crowd begins early' },
    { time: '12:00 PM', zone: 'Collins St', pct: 65, level: 'medium', reason: 'Office lunch flow' },
    { time: '1:30 PM', zone: 'Federation Square', pct: 80, level: 'high', reason: 'Event overflow' },
    { time: '2:00 PM', zone: 'Elizabeth St', pct: 42, level: 'medium', reason: 'Tram frequency increases' },
]